In [1]:
#!pip install ipython-sql # only needed if you are doing this the first time
!pip install mysqlclient # might need this when you open the file.

Collecting mysqlclient
  Downloading mysqlclient-2.1.0.tar.gz (87 kB)
     |████████████████████████████████| 87 kB 1.7 MB/s
Building wheels for collected packages: mysqlclient
  Building wheel for mysqlclient (setup.py) ... done
  Created wheel for mysqlclient: filename=mysqlclient-2.1.0-cp37-cp37m-linux_x86_64.whl size=99967 sha256=04dd93e3f1f7cd19758cc7dac1d9265c9d302bcfec23bdcf41500ae1e4059504
  Stored in directory: /root/.cache/pip/wheels/97/d4/df/08cd6e1fa4a8691b268ab254bd0fa589827ab5b65638c010b4
Successfully built mysqlclient
Installing collected packages: mysqlclient
Successfully installed mysqlclient-2.1.0

In [2]:
# Syntax for connection to postgresql (not mysql) postgresql://<username>:<password>@<hostname>/database
# We will connect to the etherium mainnet database on anyblock
# since anyblock has disabled new account creation, I am using the same username/password for everyone to access. Hope this works :) 
%load_ext sql
%sql postgresql://291ba738-366d-4650-a1ac-92590aace095:fe3ff01b-999d-4d24-9874-633c37726d99@sql.anyblock.net:5432/ethereum_ethereum_mainnet

/usr/local/lib/python3.7/dist-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)

'Connected: 291ba738-366d-4650-a1ac-92590aace095@ethereum_ethereum_mainnet'

In [3]:
# get list of all tables by excluding system tables and those not 'public'

%%sql 
SELECT *
FROM pg_catalog.pg_tables
WHERE schemaname != 'pg_catalog' AND 
    schemaname != 'information_schema' AND schemaname ='public';

 * postgresql://291ba738-366d-4650-a1ac-92590aace095:***@sql.anyblock.net:5432/ethereum_ethereum_mainnet
11 rows affected.

[('public', 'method', 'postgres', None, True, False, True, False),
 ('public', 'event', 'postgres', None, True, False, True, False),
 ('public', 'balance', 'postgres', None, True, False, True, False),
 ('public', 'trace', 'postgres', None, True, False, True, False),
 ('public', 'contract', 'postgres', None, True, False, True, False),
 ('public', 'log', 'postgres', None, True, False, True, False),
 ('public', 'call', 'postgres', None, True, False, True, False),
 ('public', 'uncle', 'postgres', None, True, False, True, False),
 ('public', 'token', 'postgres', None, True, False, True, False),
 ('public', 'tx', 'postgres', None, True, False, True, False),
 ('public', 'block', 'postgres', None, True, False, True, False)]

In [4]:
# explore any one table. Remember to always limit the rows as some of these tables are big.
%%sql 
select * from token limit 10;

 * postgresql://291ba738-366d-4650-a1ac-92590aace095:***@sql.anyblock.net:5432/ethereum_ethereum_mainnet
10 rows affected.

[('0x966daafcd90265acbf50d439d9d06bea8d83ead4', 'Virtual Augur Share', '0x966dAAfCD90265acbf50D439d9d06bea8d83EAd4', None, 'VSHARE', 'ERC-20', Decimal('0.8'), datetime.datetime(2019, 2, 23, 0, 21, 20, tzinfo=psycopg2.tz.FixedOffsetTimezone(offset=0, name=None)), datetime.datetime(2019, 2, 25, 9, 10, 48, tzinfo=psycopg2.tz.FixedOffsetTimezone(offset=0, name=None)), Decimal('18'), Decimal('66722268557130'), None),
 ('0x05ea348852864e3fa3c5e35598d2b03f03d3dfd9', 'MicrobeSafari', '0x05eA348852864E3Fa3C5E35598D2b03F03D3DfD9', [], 'MICRO', 'ERC1155', Decimal('1'), datetime.datetime(2021, 7, 22, 4, 6, 53, tzinfo=psycopg2.tz.FixedOffsetTimezone(offset=0, name=None)), datetime.datetime(2022, 3, 21, 14, 35, 31, tzinfo=psycopg2.tz.FixedOffsetTimezone(offset=0, name=None)), Decimal('0'), Decimal('0'), ['ERC1155', 'ERC165']),
 ('0x41e7dac21d8e4056b66b7d03dee4cd35f7efcc1d', 'OneSwap-Share', '0x41e7dAC21D8E4056B66b7d03DeE4CD35F7efcC1D', [], '', 'ERC20', Decimal('1'), datetime.datetime(2020, 9, 21, 10, 4, 56, tzinfo=psycopg2.tz.FixedOffsetTimezone(offset=0, name=None)), datetime.datetime(2022, 1, 20, 3, 11, 57, tzinfo=psycopg2.tz.FixedOffsetTimezone(offset=0, name=None)), Decimal('18'), Decimal('5072091409'), None),
 ('0xdb1c84309c51966dc8b25dad34ca12961049c8de', '', '0xdB1c84309c51966dc8B25DAD34cA12961049c8DE', None, None, 'ERC-721', Decimal('0.8'), datetime.datetime(2017, 12, 21, 10, 41, 19, tzinfo=psycopg2.tz.FixedOffsetTimezone(offset=0, name=None)), datetime.datetime(2019, 2, 28, 4, 23, 57, tzinfo=psycopg2.tz.FixedOffsetTimezone(offset=0, name=None)), None, None, None),
 ('0x00e3ec1f55ce4f86cf7ac2bac8c0876a276e78d2', 'LarvaDads', '0x00E3eC1F55cE4F86cF7ac2bAc8c0876A276e78D2', [], 'LDAD', 'ERC721', Decimal('1'), datetime.datetime(2022, 1, 1, 7, 13, 55, tzinfo=psycopg2.tz.FixedOffsetTimezone(offset=0, name=None)), datetime.datetime(2022, 1, 19, 7, 56, 9, tzinfo=psycopg2.tz.FixedOffsetTimezone(offset=0, name=None)), Decimal('0'), Decimal('5000'), None),
 ('0x59346466cdc1b8c3942798ba4d63d98271f1405d', 'Feike Foundation Token', '0x59346466cdc1B8c3942798bA4d63D98271F1405D', [], 'FFT', 'ERC20', Decimal('1'), datetime.datetime(2018, 5, 3, 8, 47, 53, tzinfo=psycopg2.tz.FixedOffsetTimezone(offset=0, name=None)), datetime.datetime(2022, 1, 23, 20, 43, 56, tzinfo=psycopg2.tz.FixedOffsetTimezone(offset=0, name=None)), Decimal('18'), Decimal('600000000000000000000000000000'), None),
 ('0xf24a1ca2a5621e786353d890e117b37c6145e361', 'Ruby Farm', '0xF24a1ca2a5621e786353d890E117B37C6145e361', [], '', 'ERC20', Decimal('1'), datetime.datetime(2020, 10, 12, 23, 43, 51, tzinfo=psycopg2.tz.FixedOffsetTimezone(offset=0, name=None)), datetime.datetime(2022, 1, 24, 16, 41, 18, tzinfo=psycopg2.tz.FixedOffsetTimezone(offset=0, name=None)), Decimal('0'), Decimal('0'), None),
 ('0x17d719e7706ef3a50f5518b51c73ca26367309d7', 'LARP', '0x17d719E7706eF3a50f5518B51C73cA26367309d7', [], 'LARP', 'ERC20', Decimal('1'), datetime.datetime(2020, 10, 8, 2, 28, 22, tzinfo=psycopg2.tz.FixedOffsetTimezone(offset=0, name=None)), datetime.datetime(2022, 1, 25, 5, 33, 52, tzinfo=psycopg2.tz.FixedOffsetTimezone(offset=0, name=None)), Decimal('18'), Decimal('77777000000000000000000'), None),
 ('0xbfb48ea84461a0a3627a99377b4dbee68c1e0835', ' Lever.Network', '0xbfB48eA84461a0a3627A99377b4dbee68C1E0835', [], ' LEV', None, Decimal('0.6'), datetime.datetime(2021, 5, 1, 6, 12, 40, tzinfo=psycopg2.tz.FixedOffsetTimezone(offset=0, name=None)), datetime.datetime(2022, 1, 24, 18, 14, 54, tzinfo=psycopg2.tz.FixedOffsetTimezone(offset=0, name=None)), Decimal('18'), Decimal('100000000000000000000000000'), None),
 ('0x1de04c121e2c77c89f1806620e21b1fa87bdaff4', 'THE VOYDZ', '0x1de04c121e2c77C89f1806620E21b1FA87BDAff4', [], 'V0YD', 'ERC721', Decimal('1'), datetime.datetime(2021, 12, 22, 4, 36, 8, tzinfo=psycopg2.tz.FixedOffsetTimezone(offset=0, name=None)), datetime.datetime(2022, 1, 14, 6, 25, 49, tzinfo=psycopg2.tz.FixedOffsetTimezone(offset=0, name=None)), Decimal('0'), Decimal('0'), None)]

In [5]:
# The first one is to see a table structure. You can see the structure in the ER model as well at https://docs.google.com/spreadsheets/d/1ehCIQxjSZcVLnddDWHBzhPb8h83mHWZxvyX9eckghbU/edit#gid=1071981661
%%sql 
SELECT 
   table_name, 
   column_name, 
   data_type 
FROM 
   information_schema.columns
WHERE 
   table_name = 'block';

 * postgresql://291ba738-366d-4650-a1ac-92590aace095:***@sql.anyblock.net:5432/ethereum_ethereum_mainnet
24 rows affected.

[('block', 'id', 'text'),
 ('block', 'number', 'numeric'),
 ('block', 'hash', 'text'),
 ('block', 'parent_hash', 'text'),
 ('block', 'nonce', 'text'),
 ('block', 'step', 'text'),
 ('block', 'signature', 'text'),
 ('block', 'sha3_uncles', 'text'),
 ('block', 'logs_bloom', 'text'),
 ('block', 'transactions_root', 'text'),
 ('block', 'state_root', 'text'),
 ('block', 'receipts_root', 'text'),
 ('block', 'miner', 'text'),
 ('block', 'difficulty', 'numeric'),
 ('block', 'total_difficulty', 'numeric'),
 ('block', 'extra_data', 'text'),
 ('block', 'size', 'numeric'),
 ('block', 'gas_limit', 'numeric'),
 ('block', 'gas_used', 'numeric'),
 ('block', 'timestamp', 'timestamp with time zone'),
 ('block', 'uncles', 'ARRAY'),
 ('block', 'seal_fields', 'ARRAY'),
 ('block', 'mix_hash', 'text'),
 ('block', 'base_fee_per_gas', 'numeric')]

In [6]:
%%sql 
Select count(*), block_hash from tx t 
where "to" = '0xF43Aaa80a8F9dE69bc71aeA989AfCeB8DB7b690F'
group by block_hash
order by count(*) desc
limit 1;

 * postgresql://291ba738-366d-4650-a1ac-92590aace095:***@sql.anyblock.net:5432/ethereum_ethereum_mainnet
1 rows affected.

[(6, '0x53859d8f11cf7a62f4b1a1c63bbe738d3413cc03fa6500c764535b27acd3cd44')]

# 1. Find the latest block and the length of the block

In [11]:
#Finding the latest block will help for finding out the ongoin trends and patterns either in transaction or 
#number of new tokens/nft's sold. And can help us investing in the right asset.
%%sql
SELECT * FROM block ORDER BY number DESC LIMIT 1

 * postgresql://291ba738-366d-4650-a1ac-92590aace095:***@sql.anyblock.net:5432/ethereum_ethereum_mainnet
1 rows affected.

[('0xad5f0bc4ad668b7e531e3b2ff6ff83c32a12c9765b773b86d11dbcde61053d58', Decimal('14651438'), '0xad5f0bc4ad668b7e531e3b2ff6ff83c32a12c9765b773b86d11dbcde61053d58', '0xffd1119c70477551518ca3d101f756e80f7c34f4eaddb57cecba88383cd7b6ef', '0xc04d1500065eb5e3', None, None, '0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347', '0xf7fe7bcfffa75bb5d8ff37dafe7fbf7ffdc0e4bb1e9f6e6e677de4efdfbbc7cfdffec7ffc1ccabf8a584fbf8591b19662b3b9bdfbe9cfda9c718b4cf03bbfc13ede3e8bffba38dfefff ... (216 characters truncated) ... bbd526fe476defeef5ef445d5efbe4f3a7b5f922bcb2e8ebb5c87febc5e15fb3fb435402d9baedbcbf1eb597ca93bbe7bdda59bc7932fe7b65af21c7cdc6b7145e7f7c4fefd996995f8f7', '0xb27576a777c57805f31c6a7c353fb13dfcb44498e7cbf913a2d21cd3c6ce9bda', '0xd317f754a2f2babb4ee43702ca7795193a9c08bf4a1eb8a40e80f61fca64f41c', '0xead701594ef60e80b5280b91b0fb5d72aac62689452029c6eb245a694355f9fa', '0x7f101fe45e6649a6fb8f3f8b43ed03d353f2b90c', Decimal('13859876081592781'), Decimal('47255017377997769466310'), '0x466c6578706f6f6c2f53302f55532d45617374202d20486f6e67204b6f6e67', Decimal('148168'), Decimal('29999972'), Decimal('29663483'), datetime.datetime(2022, 4, 25, 3, 25, 38, tzinfo=psycopg2.tz.FixedOffsetTimezone(offset=0, name=None)), [], None, '0x2f60cbd6e6c717fd2df5653b328184c435529712431fd78ca4dfaa4a57984314', Decimal('22663531641'))]

### This will show the whole block. But you can use a shorter form:

In [12]:
%%sql
SELECT max(number) FROM block

 * postgresql://291ba738-366d-4650-a1ac-92590aace095:***@sql.anyblock.net:5432/ethereum_ethereum_mainnet
1 rows affected.

[(Decimal('14651439'),)]

# 2. Find events for a given block

In [14]:
# Events are called Events because they are very good at signalling that an event has taken place. 
#In blockchain terms, they’re cheap. They’re cheap to write in a contract in terms of deployment cost and gas cost when calling a function with an event, 
#and they’re free to read. In short, they’re a very good way of broadcasting relevant information.
%%sql
SELECT * FROM event
WHERE event.block_number=7075271
Limit 10

 * postgresql://291ba738-366d-4650-a1ac-92590aace095:***@sql.anyblock.net:5432/ethereum_ethereum_mainnet
10 rows affected.

[('0x2340df3f23ac94127fefaac70dad8a047c40cfdf592537a8d9193301b38435cf', [{'hex': '0xBffcCDe66c587C134A0D417941aAE7e8De309592', 'pos': 0, 'name': 'sender', 'type': 'address'}, {'hex': '0x883c934221800', 'num': 2396700000000000, 'pos': 1, 'name': 'value', 'type': 'uint256'}], 'Deposit', Decimal('6'), Decimal('6'), '0xd0af72ee7294a7eb251cccddb12835b2876d0e6febdfa22e24146d3a77cd0f21', '0x97b9b5bae3ef6dd07bc808a18e47867dafb30913ecd6d8a3d889b29e34b9a1c8', Decimal('7075271'), '0x51CA21eD46a9DF3Cb6F34624CBd482d312996730', Decimal('0.9'), datetime.datetime(2019, 1, 16, 9, 36, 58, tzinfo=psycopg2.tz.FixedOffsetTimezone(offset=0, name=None))),
 ('0x4ce0fc9d12478377f2fb48c642cb15fac170f69a8c01b116c16c540bfbde10f3', [{'hex': '0xeb7827AbeA70C819C89d9313F16d58C5bD4ce7BB', 'pos': 0, 'name': 'beneficiary', 'type': 'address'}, {'hex': '0xe390e3bf0a2599', 'num': 64054127550408089, 'pos': 1, 'name': 'value', 'type': 'uint256'}], 'Mine', Decimal('53'), Decimal('71'), '0x1a9914930e8068ecec903e0c0115d20219b8a5ebab820f57bbd81d89fe423bd1', '0x97b9b5bae3ef6dd07bc808a18e47867dafb30913ecd6d8a3d889b29e34b9a1c8', Decimal('7075271'), '0xD97E471695f73d8186dEABc1AB5B8765e667Cd96', Decimal('0.9'), datetime.datetime(2019, 1, 16, 9, 36, 58, tzinfo=psycopg2.tz.FixedOffsetTimezone(offset=0, name=None))),
 ('0xadeb18f60d3d6a4998cb27c695b42094286634671b90c4fc6c03f5980ffd9ba3', [{'hex': '0x3b521a0Df56465078f5D2319756FD26c4DCc09c1', 'pos': 0, 'name': 'from', 'type': 'address'}, {'hex': '0x03cb0021808442Ad5EFb61197966aef72a1deF ... (17 characters truncated) ... ame': 'to', 'type': 'address'}, {'hex': '0x27f7d0bdb920000', 'num': 180000000000000000, 'pos': 2, 'name': 'value', 'type': 'uint256', 'scaled': 0.18}], 'Transfer', Decimal('37'), Decimal('52'), '0xd3b75b853c7f7ce3cb00f850ad8f6c23f334ddae3bb0f743c1cf417d293d6e86', '0x97b9b5bae3ef6dd07bc808a18e47867dafb30913ecd6d8a3d889b29e34b9a1c8', Decimal('7075271'), '0x03cb0021808442Ad5EFb61197966aef72a1deF96', Decimal('0.6'), datetime.datetime(2019, 1, 16, 9, 36, 58, tzinfo=psycopg2.tz.FixedOffsetTimezone(offset=0, name=None))),
 ('0x860664f28dbfb4a2946ae5c5a247b6f33fb5c0cce4566a2082f149ba09e33b91', [{'hex': '0x3f5CE5FBFe3E9af3971dD833D26bA9b5C936f0bE', 'pos': 0, 'name': 'from', 'type': 'address'}, {'hex': '0x28d7a2e845f98000', 'num': 2943000000000000000, 'pos': 1, 'name': 'value', 'type': 'uint256'}, {'hex': '0x', 'pos': 2, 'name': 'data', 'type': 'bytes'}], 'ForwarderDeposited', Decimal('17'), Decimal('22'), '0xb0dda9dad54e845fc3fea2bba2ea284097f2ecca43160006b8fe16269a88cc00', '0x97b9b5bae3ef6dd07bc808a18e47867dafb30913ecd6d8a3d889b29e34b9a1c8', Decimal('7075271'), '0xbc7acAF41BC6265Eff9f8cfb540d6b797785926A', Decimal('0.9'), datetime.datetime(2019, 1, 16, 9, 36, 58, tzinfo=psycopg2.tz.FixedOffsetTimezone(offset=0, name=None))),
 ('0xf41169540aa0b5f596983de1c55e267b172a35f6ebc992fda94dc36d2c583205', [{'hex': '0x32Be343B94f860124dC4fEe278FDCBD38C102D88', 'pos': 0, 'name': 'a', 'type': 'address'}], 'e', Decimal('7'), Decimal('7'), '0xfedbc680751051a8b557e9d477c5c22a6b2005a9bf229605135c8bad3aa74269', '0x97b9b5bae3ef6dd07bc808a18e47867dafb30913ecd6d8a3d889b29e34b9a1c8', Decimal('7075271'), '0x209c4784AB1E8183Cf58cA33cb740efbF3FC18EF', Decimal('0.2'), datetime.datetime(2019, 1, 16, 9, 36, 58, tzinfo=psycopg2.tz.FixedOffsetTimezone(offset=0, name=None))),
 ('0x32ef2da6be393e70db0ce9c0c44e71c1ee75788ead4b8a6fa03654864ffbaeac', [{'hex': '0x118eF37556C0772f4e7bC17c91c8a0b8bd95a08A', 'pos': 0, 'name': 'from', 'type': 'address'}, {'hex': '0xEf5cfb1748724fd124F55BB414a8cd58f7774a ... (15 characters truncated) ... 'name': 'to', 'type': 'address'}, {'hex': '0x2c2e1214c1', 'num': 189751497921, 'pos': 2, 'name': 'value', 'type': 'uint256', 'scaled': 189.751497921}], 'Transfer', Decimal('30'), Decimal('42'), '0x613df9468e0fe072dabd6534a834949736f5f1b69d116ec9a84098f6163833f8', '0x97b9b5bae3ef6dd07bc808a18e47867dafb30913ecd6d8a3d889b29e34b9a1c8', Decimal('7075271'), '0x0e50e6d6bB434938D8fE670a2d7A14Cd128eB50f', Decimal('0.5'), datetime.datetime(2019, 1, 16, 9, 36, 58, tzinfo=psycopg2.tz.FixedOffsetTimezone(offset=0, name=None))),
 ('0x1bf2a800887d1bf041384a392359ad02797c35be498c516bdc6deec8bd820801', [{'hex': '0xbc7acAF41BC6265Eff9f8cfb540d6b797785926A', 'pos': 0, 'name': 'from', 'type': 'address'}, {'hex': '0x28d7a2e845f98000', 'num': 2943000000000000000, 'pos': 1, 'name': 'value', 'type': 'uint256'}, {'hex': '0x', 'pos': 2, 'name': 'data', 'type': 'bytes'}], 'Deposited', Decimal('16'), Decimal('22'), '0xb0dda9dad54e845fc3fea2bba2ea284097f2ecca43160006b8fe16269a88cc00', '0x97b9b5bae3ef6dd07bc808a18e47867dafb30913ecd6d8a3d889b29e34b9a1c8', Decimal('7075271'), '0x1522900B6daFac587d499a862861C0869Be6E428', Decimal('0.4'), datetime.datetime(2019, 1, 16, 9, 36, 58, tzinfo=psycopg2.tz.FixedOffsetTimezone(offset=0, name=None))),
 ('0x32aa19f8e70e0dfd724dc64bea2cac6e4ad6f8bba9f87238e6169ac34ab2f7ff', [{'hex': '0x521dB06bF657Ed1D6C98553A70319a8DdBAc75A3', 'pos': 0, 'name': 'from', 'type': 'address'}, {'hex': '0x5c3848B3611589Fce43e9fd13Beb9Ee870127b ... (38 characters truncated) ... address'}, {'hex': '0xd6fbf73b40400c8d800000', 'num': 259900000000000000000000000, 'pos': 2, 'name': 'value', 'type': 'uint256', 'scaled': 259900000}], 'Transfer', Decimal('22'), Decimal('31'), '0xbbff8456333fe86fef3d2c77a9e90e702fba8570523c8eadbdde0e5730a2f95d', '0x97b9b5bae3ef6dd07bc808a18e47867dafb30913ecd6d8a3d889b29e34b9a1c8', Decimal('7075271'), '0x2F141Ce366a2462f02cEA3D12CF93E4DCa49e4Fd', Decimal('0.5'), datetime.datetime(2019, 1, 16, 9, 36, 58, tzinfo=psycopg2.tz.FixedOffsetTimezone(offset=0, name=None))),
 ('0x341cdbf7f1d112fe3f86b637ba88a266b7a2e83a504d3a7df9d2b04daab4b6b8', [{'hex': '0xD551234Ae421e3BCBA99A0Da6d736074f22192FF', 'pos': 0, 'name': 'from', 'type': 'address'}, {'hex': '0xb064f0C59d7D0491220Ad80158C48ECC791503 ... (27 characters truncated) ... , 'type': 'address'}, {'hex': '0xf997b1bd0fd6410000', 'num': 4604170000000000000000, 'pos': 2, 'name': 'value', 'type': 'uint256', 'scaled': 4604.17}], 'Transfer', Decimal('12'), Decimal('14'), '0xb1a012c5c07cb8fe26d7db1c1e74235f693f3d46a5e7fd8d6a8ab9ce04aa1118', '0x97b9b5bae3ef6dd07bc808a18e47867dafb30913ecd6d8a3d889b29e34b9a1c8', Decimal('7075271'), '0x5CA9a71B1d01849C0a95490Cc00559717fCF0D1d', Decimal('0.6'), datetime.datetime(2019, 1, 16, 9, 36, 58, tzinfo=psycopg2.tz.FixedOffsetTimezone(offset=0, name=None))),
 ('0x3d8885ef0abb17955827c9e67b54de23d093e1bc17a7dd0598c3b26af93c9c13', [{'hex': '0x70000000000001a1000000000000000000000000000000000000000000000000', 'num': 5065903904132583811536372959754683820532980776881464228194491334 ... (183 characters truncated) ... 16037C2EF4187D572e00D4303E5413b1', 'pos': 2, 'name': 'to', 'type': 'address'}, {'hex': '0x1', 'num': 1, 'pos': 3, 'name': 'value', 'type': 'uint256'}], 'Transfer', Decimal('57'), Decimal('82'), '0xb7179b24c0a51605323ddde5971840d95b1ed0d6c338d53f7c0045c19810a55c', '0x97b9b5bae3ef6dd07bc808a18e47867dafb30913ecd6d8a3d889b29e34b9a1c8', Decimal('7075271'), '0x8562c38485B1E8cCd82E44F89823dA76C98eb0Ab', Decimal('0.2'), datetime.datetime(2019, 1, 16, 9, 36, 58, tzinfo=psycopg2.tz.FixedOffsetTimezone(offset=0, name=None)))]

# 3. Find calls for transaction hash and transactions for a given contract

### I used TenXPay as the address of  contract:

In [15]:
#Every transaction on the blockchain has its unique identifier called transaction hash (tx hash, TX ID) Transaction hash looks like a random sequence of letters and/or numbers.
%%sql
SELECT * FROM call
WHERE call.hash = '0xadd837afa5b68987eb9f0167ad65cbb8131f57da84db56a19acf4a5a98bd35da'

 * postgresql://291ba738-366d-4650-a1ac-92590aace095:***@sql.anyblock.net:5432/ethereum_ethereum_mainnet
1 rows affected.

[('0xadd837afa5b68987eb9f0167ad65cbb8131f57da84db56a19acf4a5a98bd35da', [{'hex': '0x5f8e427c54d95fDc0E5D1834df386A8374162080', 'pos': 0, 'name': 'to', 'type': 'address'}, {'hex': '0x1158e460913d00000', 'num': 20000000000000000000, 'pos': 1, 'name': 'value', 'type': 'uint256', 'scaled': 20}], '0x0cc29246f1185045028a8a7163a3752b61333aee8fa904b4645ecbd6203fe848', Decimal('5718174'), '0x831164a5164c7c4c6c95826cfec637140255ddc4', '0xadd837afa5b68987eb9f0167ad65cbb8131f57da84db56a19acf4a5a98bd35da', 'transfer', '0xfe5f141bf94fe84bc28ded0ab966c16b17490657', Decimal('143'), Decimal('0.6'), datetime.datetime(2018, 6, 2, 6, 46, 11, tzinfo=psycopg2.tz.FixedOffsetTimezone(offset=0, name=None)), True)]

In [27]:
%%sql
SELECT * FROM tx
WHERE tx.to='0xB97048628DB6B661D4C2aA833e95Dbe1A905B280'
LIMIT 10

 * postgresql://291ba738-366d-4650-a1ac-92590aace095:***@sql.anyblock.net:5432/ethereum_ethereum_mainnet
10 rows affected.

[('0xdfd7aab9bfcc252dcfa50133422c808a49f269c763d054733e1109f8a9765a3a', '0x81cb66480aed9988b97cb96beb4b3906a073717ba76c2b6793ea7af4853029e5', Decimal('7104735'), '0x5935eb9F59c8f5854c3F4857fB47f4a8D7322e64', Decimal('110000'), Decimal('4000200000'), '0xdfd7aab9bfcc252dcfa50133422c808a49f269c763d054733e1109f8a9765a3a', None, '0x7f67611462c5aae5a2e3d8cce6e0ae5c102976f058d5bd0d452ea7c8a2e827860e82d5cd776764c20499d325109876479924e2eda94c5ab9e1656927304b83b7', '0xa9059cbb0000000000000000000000000d0707963952f2fba59dd06f2b425ace40b492fe0000000000000000000000000000000000000000000001b1a06cb77b4d9c0000', Decimal('234'), '0xB97048628DB6B661D4C2aA833e95Dbe1A905B280', Decimal('175'), Decimal('0'), datetime.datetime(2019, 1, 21, 17, 26, 37, tzinfo=psycopg2.tz.FixedOffsetTimezone(offset=0, name=None)), '0x25', '0x8db981f0d60922c75c7135c3da7c3e04324f986dfa5d6a13f40041f38c78d5aa', '0x4580cac4655bc6fa7bc6e23520a538edcae26d75684c96171f2c7389aa49bd20', None, Decimal('7911481'), Decimal('22129'), '0x000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000040000000000000 ... (216 characters truncated) ... 00000000000000000000000000002000000000000000000000040000000000000000000000800000000000000000000000000000000000000000000000000000000000000000000000000', None, True, None, None, None, None, None, None),
 ('0xbc66f78b40d6af6bc0010f5fedc8804fe9b8a374ae95bf9302d99443fc8da9b3', '0xd9a19a8e672a7a24925c309446534aacbc51296eb488e5f4e05eb5372d804d1f', Decimal('7088032'), '0x0eb20fF2Bbf3603833139A256E5e5cC5Ca663479', Decimal('110000'), Decimal('60000000000'), '0xbc66f78b40d6af6bc0010f5fedc8804fe9b8a374ae95bf9302d99443fc8da9b3', None, '0x99e6e0e639b02cc3183cc07680623a672a236ce9efbf408cbfc15136fb759a4ea990330e73be711d609a898d7f5dd7e7c06dc30e8571b4553a3afd24d93e06fa', '0xa9059cbb000000000000000000000000fa28f4130e6929b9bd801e8e3c332ed9005fafa40000000000000000000000000000000000000000000006cacf05ad4e5c200000', Decimal('597'), '0xB97048628DB6B661D4C2aA833e95Dbe1A905B280', Decimal('4'), Decimal('0'), datetime.datetime(2019, 1, 18, 16, 30, 22, tzinfo=psycopg2.tz.FixedOffsetTimezone(offset=0, name=None)), '0x25', '0x3f3b5e7e76dfa94e9479da17d3c326c9a4da48be53347ef0ad448d7e53cf621a', '0x3642b598f9ea26a31eb74daad9042d03232c6b4d215421b84c136db2174d4397', None, Decimal('123816'), Decimal('22065'), '0x002000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 ... (216 characters truncated) ... 00000000000000000000000000002000000000000001000000000000000000000000000000000000000000000000000000000000000000000000000000000000004000000000000000000', None, True, None, None, None, None, None, None),
 ('0x2b41e63f9f2d975730752152760da33823547fa88df9224dbe2686130ade1c26', '0x027b6d72cc4b57ccc013a852a755301b8bb202f5ebe810b7f482f8bbd11d77a9', Decimal('4224121'), '0xFBb1b73C4f0BDa4f67dcA266ce6Ef42f520fBB98', Decimal('187130'), Decimal('53254687500'), '0x2b41e63f9f2d975730752152760da33823547fa88df9224dbe2686130ade1c26', None, '0x8178af6e1ae9a747de289f2106a85875288b24a2c6bdb1f069cad506409abdd4f1bd1ac05507615c852a9a74cf3013f7b13b9e0f03870011993e575a357a308d', '0xa9059cbb000000000000000000000000227bafc8a5bd5c3837b747b9a17a60a1c29d43a20000000000000000000000000000000000000000000000167ac148a3144d9c00', Decimal('1269671'), '0xB97048628DB6B661D4C2aA833e95Dbe1A905B280', Decimal('122'), Decimal('0'), datetime.datetime(2017, 8, 31, 17, 45, 8, tzinfo=psycopg2.tz.FixedOffsetTimezone(offset=0, name=None)), '0x25', '0xe8b5285949ceaabfdadd10a9ff71e1c9c3b6863ece6b4c545bc6b3eae08c3ecb', '0x191e66f85ef4b18d3b29bd8257a54fc673d6f9ddb37f98e9961c4ced2a7c66ec', None, Decimal('5543712'), Decimal('37129'), '0x000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 ... (216 characters truncated) ... 00000000000000000000000000002000000000000008000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000', '0xfb0e4f2870a243b1935348f04640f6d2e3371405f35e80721dd7de82f19040f2', None, None, None, None, None, None, None),
 ('0x75baf78e29bdec25d671777bdb789f83dfd3e5a092673ab75ccfc0e076343a46', '0x4a2aef67cd37c36954caade2b4369d35152f9744c9d075925e85acef9cfd17d6', Decimal('4267008'), '0xFBb1b73C4f0BDa4f67dcA266ce6Ef42f520fBB98', Decimal('201938'), Decimal('51000000000'), '0x75baf78e29bdec25d671777bdb789f83dfd3e5a092673ab75ccfc0e076343a46', None, '0x8178af6e1ae9a747de289f2106a85875288b24a2c6bdb1f069cad506409abdd4f1bd1ac05507615c852a9a74cf3013f7b13b9e0f03870011993e575a357a308d', '0xa9059cbb000000000000000000000000daae924a458ed16f85000e418d9615fd46bda0620000000000000000000000000000000000000000000000008aa39c121a270000', Decimal('1547308'), '0xB97048628DB6B661D4C2aA833e95Dbe1A905B280', Decimal('21'), Decimal('0'), datetime.datetime(2017, 9, 12, 19, 41, 42, tzinfo=psycopg2.tz.FixedOffsetTimezone(offset=0, name=None)), '0x25', '0x519e9fc5abfef3cae55ac8a4aaa03ae03734bda8105bbbd19a676182969e9d07', '0x6a657d3ab789066e7b6465eb3be32b0e73ac5deb63cb4db2c4c83b50d631d07e', None, Decimal('1025425'), Decimal('51937'), '0x000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 ... (216 characters truncated) ... 00000000000000000000000000002000000000000000000000000000000000000000000001000020000000000000000200000000000000000000000000000000000000000000000000000', '0xdfecee0868fe45274f904bf960094125218540f1d9e2033388e86ee5ba363b92', None, None, None, None, None, None, None),
 ('0x572adf417b7f93600df161df6e0483f04557cc79be3bba5b32624c3961d6211b', '0x8b5bbd241c2c7668f07f1807e6246ffc17b9d81ac45ef81370fb5beb40850b05', Decimal('6953366'), '0xFBb1b73C4f0BDa4f67dcA266ce6Ef42f520fBB98', Decimal('150000'), Decimal('50000000000'), '0x572adf417b7f93600df161df6e0483f04557cc79be3bba5b32624c3961d6211b', None, '0x8178af6e1ae9a747de289f2106a85875288b24a2c6bdb1f069cad506409abdd4f1bd1ac05507615c852a9a74cf3013f7b13b9e0f03870011993e575a357a308d', '0xa9059cbb0000000000000000000000000c2b4a9e76b736960be26842fb070a06e217ffb5000000000000000000000000000000000000000000000023b6dfc227a0be3400', Decimal('7048206'), '0xB97048628DB6B661D4C2aA833e95Dbe1A905B280', Decimal('6'), Decimal('0'), datetime.datetime(2018, 12, 26, 1, 11, 46, tzinfo=psycopg2.tz.FixedOffsetTimezone(offset=0, name=None)), '0x26', '0xff0441524232f4039d68184fcc058675bc3b8a4a6248deaddf7cf2cba7941737', '0x1594cf0a9d67694e80877c2f40e00321279e27b237363f293ba080207499b45e', None, Decimal('368950'), Decimal('37129'), '0x000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000800000000000000000000 ... (216 characters truncated) ... 00000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000', None, True, None, None, None, None, None, None),
 ('0x523a766fcf226120469341d254747393590202f3bd99e08159852cecf93b4b2b', '0x13a03ffd02d4f411bd2b90dcaa235194417d6135a348147b41c1827761d12186', Decimal('4309978'), '0x1fCAc8054aEDeCcdB6DA04AF0B5Ec54E4Cb2bFfe', Decimal('52065'), Decimal('21152319932'), '0x523a766fcf226120469341d254747393590202f3bd99e08159852cecf93b4b2b', None, '0x1d519f1497711f94741034db46940a35288384dcb1fa251306a339d73e0b179480bcbd8a8a51453ab2f434260b3399d5a9f69bb571cac809b6cf8db136e68045', '0xa9059cbb000000000000000000000000cc55751998941d6968492af6260054e44d0d5a2800000000000000000000000000000000000000000000000357b978f5bfcc1400', Decimal('3528'), '0xB97048628DB6B661D4C2aA833e95Dbe1A905B280', Decimal('34'), Decimal('0'), datetime.datetime(2017, 9, 25, 9, 11, 13, tzinfo=psycopg2.tz.FixedOffsetTimezone(offset=0, name=None)), '0x25', '0xa863fc5fea086038152bc921eaeeb4adb41b4bf7f79713934ade5974b673a5b6', '0x73ec4d7b0e267cbd398f4e94e6ae9674ae1402336574bf9cb3272938605c96f6', None, Decimal('876297'), Decimal('52065'), '0x000000000000000000000000000000000000000000004000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 ... (216 characters truncated) ... 00000000000000000000000000002000000000000000000000000000000000000000000000000400000000000000000000000000000000010000000000000000400000000000000000000', '0x3602da288833e025137f579aa77acce4e1ae1f8d9e9842feff9d7d704b5b7c65', None, None, None, None, None, None, None),
 ('0x4f81cb0c43607efd40006fcc50953a19eb7aa7cdc5a285793f1adbe3396ec481', '0xa42b02b52fbf2d1856f0c6bab8f6300bca72a38b918ecd9bb40567b65d4b7fbd', Decimal('4655669'), '0x6A6eb0a1fC2dcC0eDe58DDCcA846dc7928c7053a', Decimal('420000'), Decimal('2000000000'), '0x4f81cb0c43607efd40006fcc50953a19eb7aa7cdc5a285793f1adbe3396ec481', None, '0xf05b89de81dd6602fee60d8a76944ed6e5afe17de2b6f197766992da73ee993a8ea552880a020c0555a17b785e5c49a098264ec1469e78db6a3e83e672db47c7', '0xa9059cbb000000000000000000000000236f9f97e0e62388479bf9e5ba4889e46b0273c3000000000000000000000000000000000000000000000017aedf5754ed8e0000', Decimal('1'), '0xB97048628DB6B661D4C2aA833e95Dbe1A905B280', Decimal('70'), Decimal('0'), datetime.datetime(2017, 12, 1, 10, 45, 30, tzinfo=psycopg2.tz.FixedOffsetTimezone(offset=0, name=None)), '0x26', '0x6e01dad37dcb53fedde5c2979090dcb205c47d879185b886612bbf6eebd600a0', '0x3c5ce99c0675a59b5218313ed9c2d95ec84821e77fc785b7cad2f352c3e40d9a', None, Decimal('4692629'), Decimal('22065'), '0x000000000000000000000000000000000000000000000000000000000000000000000000040000000000000000000080000000000000000000000000000000000000000000000000000 ... (216 characters truncated) ... 00000000000000000000008000002000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000', None, True, None, None, None, None, None, None),
 ('0xb27f6f960862abc65086bc485f1ab6e98867009629b764dd96451fd6435d5a2a', '0xee7f6e1b068a65d866e96c0cdd61e1309ac6253689cfa267bb21d2f5c2c566ab', Decimal('5004827'), '0x2B391e9381073D5E2d518944C7A9bf3e162c1d60', Decimal('120000'), Decimal('3000000000'), '0xb27f6f960862abc65086bc485f1ab6e98867009629b764dd96451fd6435d5a2a', None, '0xef6215ceacce97abd938b0b425fd30b18f8008e05e458136e4efd283397c6667fb788b48bd3bafb4b40d0a9732bd261170bc323fbe408f8325fa1fe244db691b', '0xa9059cbb0000000000000000000000002984581ece53a4390d1f568673cf693139c970490000000000000000000000000000000000000000000000365955103b65464c00', Decimal('0'), '0xB97048628DB6B661D4C2aA833e95Dbe1A905B280', Decimal('113'), Decimal('0'), datetime.datetime(2018, 1, 31, 9, 14, 48, tzinfo=psycopg2.tz.FixedOffsetTimezone(offset=0, name=None)), '0x26', '0xb8860c56bbf5d5e3ff8bc090ab242122127c8087f91b798197c822f67888909', '0x36b39de53c34269acaf6a17f0fa9461779995c68f70b4b5cdaeb35811655f368', None, Decimal('6380503'), Decimal('22129'), '0x000000000000000000000000040000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 ... (216 characters truncated) ... 00000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000', None, True, None, None, None, None, None, None),
 ('0x8ad8d9be477a9b76065fbf362e56e22b03a9f64210114833a1c84d4d3b13164e', '0x56eff5e6244a01f43b4a97e5285e24877ac3eb43b8d298b4d9d0dea36805268f', Decimal('5601321'), '0x72905cbB400386e1aA4D7f671c899f34758bcAb4', Decimal('52129'), Decimal('10000000000'), '0x8ad8d9be477a9b76065fbf362e56e22b03a9f64210114833a1c84d4d3b13164e', None, '0xcd05951e457460d24c53ac0f785635124e2c65a97f283f807e3a82771908fa4d263bcfcc019142bd00ff31ab748baa0a42030dcacafa68ea82d562468b529278', '0xa9059cbb000000000000000000000000b8029c28bfa6732c4ca144fdf637584877df87c70000000000000000000000000000000000000000000000a07584320757278000', Decimal('5'), '0xB97048628DB6B661D4C2aA833e95Dbe1A905B280', Decimal('55'), Decimal('0'), datetime.datetime(2018, 5, 12, 15, 3, 35, tzinfo=psycopg2.tz.FixedOffsetTimezone(offset=0, name=None)), '0x26', '0x9aa017689cd9f67fd3e5e06a0689e11efe310b32f6a02464ed3fa89aebf318ec', '0x41907083e704b8a6e98e78cc8355eae9e18dd4936524623abaaf6d1d3e87018', None, Decimal('4543167'), Decimal('37129'), '0x000000000000000800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 ... (216 characters truncated) ... 00000000000000000000000000002000000000000000000000000040000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000', None, True, None, None, None, None, None, None),
 ('0xc8fb87024ef5f0da001fcfb614cf505d56db0a2aa9795319aa7fc32f2caeadd9', '0xc42fca956c9f1dca3a6bc3da4e488d07454e960cb840b795fa5a386f8a9fddd6', Decimal('6484980'), '0x66adA56277ddf8409975A2e1129A972aDd738C95', Decimal('46169'), Decimal('7000000000'), '0xc8fb87024ef5f0da001fcfb614cf505d56db0a2aa9795319aa7fc32f2caeadd9', None, '0x25d64d4caab98f80675b0a3948aa0865b977c59a1d2cb020b1b9eb6f25ac4e06f1cc71221ea366c21fd972acfeb4529fb6badb10e51e1836af1b34d668c72451', '0x095ea7b30000000000000000000000001fcac8054aedeccdb6da04af0b5ec54e4cb2bffe0000000000000000000000000000000000000000204fce5e3e25026110000000', Decimal('0'), '0xB97048628DB6B661D4C2aA833e95Dbe1A905B280', Decimal('32'), Decimal('0'), datetime.datetime(2018, 10, 9, 21, 29, 41, tzinfo=psycopg2.tz.FixedOffsetTimezone(offset=0, name=None)), '0x25', '0xc8aeed67a4b89b9cd0ddee116a8709a974f961c05f420ad7dab87e468e995e26', '0x5c306d1801f2323f3b380cd9fa148f6d16764dfab5864d00c3ffe28db1192742', None, Decimal('5372204'), Decimal('46169'), '0x000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002000000000000400000000000 ... (216 characters truncated) ... 00000000000000000000000000000000000000000000000000000000000000000000000000000400000000010001000000000000000000010000000000000000400000000000000000000', None, True, None, None, None, None, None, None)]

# 4. Find specific events for a given contract

### I used the address of the TenXPay token contract again, however we would like to know the values of transfers greater than 1ETH:

In [26]:
# Specific events for given contract will help me to understand the Smart contract return values for the user interface, Asynchronous triggers with data
# and A cheaper form of storage.
%%sql
SELECT arg->'scaled', arg->'num'
FROM "event",jsonb_array_elements(args) arg
WHERE event = 'Transfer' AND address = '0xB97048628DB6B661D4C2aA833e95Dbe1A905B280'
AND (arg->'num')::numeric > 1000000000000000000
LIMIT 10

 * postgresql://291ba738-366d-4650-a1ac-92590aace095:***@sql.anyblock.net:5432/ethereum_ethereum_mainnet
10 rows affected.

[(333, 333000000000000000000),
 (10, 10000000000000000000),
 (360, 360000000000000000000),
 (837.49167, 837491670000000000000),
 (4250, 4250000000000000000000),
 (11.37183624, 11371836240000000000),
 (1500, 1500000000000000000000),
 (55.9690875, 55969087500000000000),
 (41.5, 41500000000000000000),
 (245.45469467, 245454694670000000000)]

# 5. Find the latest 10 Dai Transfer events and extract sender, receiver and value from JSON

In [20]:
# The latest Dai Transfer will help me understand Staking of idle tokens to produce interest income, Borrowing DAI to buy other coins, 
#Using it as a stable investment to hold profits from other token sales and For in-game purchases.
%%sql
SELECT
      *,
      args->0->>'hex' as "from",
      args->1->>'hex' as "to",
      CAST(args->2->'scaled' AS NUMERIC) AS "value"
FROM event
WHERE address = '0xB97048628DB6B661D4C2aA833e95Dbe1A905B280'
AND event = 'Transfer'
ORDER BY timestamp DESC
LIMIT 10

 * postgresql://291ba738-366d-4650-a1ac-92590aace095:***@sql.anyblock.net:5432/ethereum_ethereum_mainnet
10 rows affected.

[('0xc17cf3d70ea6c946844beff8bd0dc2235340731d7f6b1a035b66995cecb332f4', [{'hex': '0x25CCBB84Cb81b885a5e64CcC3f6aDa3FA37EE8f0', 'pos': 0, 'name': 'from', 'type': 'address'}, {'hex': '0xFBb1b73C4f0BDa4f67dcA266ce6Ef42f520fBB ... (31 characters truncated) ... ype': 'address'}, {'hex': '0x30b68518d0d0d89c00', 'num': 898595661110000000000, 'pos': 2, 'name': 'value', 'type': 'uint256', 'scaled': 898.59566111}], 'Transfer', Decimal('96'), Decimal('32'), '0x1233c5617ebb0749fe6fc6d7aff5bcf9d24f1afae676cddd083c17e349d96a93', '0xf65f9ba37025b420ebd8b6f0425ec92ca57c4cd6370ae5a781e9465a08fad85d', Decimal('14648937'), '0xB97048628DB6B661D4C2aA833e95Dbe1A905B280', Decimal('1'), datetime.datetime(2022, 4, 24, 18, 8, 8, tzinfo=psycopg2.tz.FixedOffsetTimezone(offset=0, name=None)), '0x25CCBB84Cb81b885a5e64CcC3f6aDa3FA37EE8f0', '0xFBb1b73C4f0BDa4f67dcA266ce6Ef42f520fBB98', Decimal('898.59566111')),
 ('0x9c9a6fdec302354c6e6b434aecf830ca864822ba849a29cce56062ecb7356099', [{'hex': '0xEeEC2e3418B21dE1881Fa09b04e9cb5F91aAbe97', 'pos': 0, 'name': 'from', 'type': 'address'}, {'hex': '0x25CCBB84Cb81b885a5e64CcC3f6aDa3FA37EE8 ... (36 characters truncated) ...  'address'}, {'hex': '0x30b68518d324e44c00', 'num': 898595661119999986688, 'pos': 2, 'name': 'value', 'type': 'uint256', 'scaled': 898.5956611199999}], 'Transfer', Decimal('180'), Decimal('106'), '0x52d4327044411873caf728cedc672f698c633432b8507a0a56a1eec61a2f761f', '0x6c6d5ba8cf8de1d84c62975ca64eed49dd2dfeee8c031be9c0d3a4f78b8862a9', Decimal('14648920'), '0xB97048628DB6B661D4C2aA833e95Dbe1A905B280', Decimal('1'), datetime.datetime(2022, 4, 24, 18, 4, 8, tzinfo=psycopg2.tz.FixedOffsetTimezone(offset=0, name=None)), '0xEeEC2e3418B21dE1881Fa09b04e9cb5F91aAbe97', '0x25CCBB84Cb81b885a5e64CcC3f6aDa3FA37EE8f0', Decimal('898.595661119999986688')),
 ('0xc0fb315ca1f56a57c1d2b69f616c086f0dd9d7da0996633563b4a1dc4274a1c7', [{'hex': '0x48EceA69E8fe2158772Eaca4eb067E797F5Dcd91', 'pos': 0, 'name': 'from', 'type': 'address'}, {'hex': '0x7079c7CcFF85824BC79Fe54A3367fDDB45B1f1 ... (33 characters truncated) ... e': 'address'}, {'hex': '0x7730ce85836e75c400', 'num': 2198679439930000000000, 'pos': 2, 'name': 'value', 'type': 'uint256', 'scaled': 2198.67943993}], 'Transfer', Decimal('275'), Decimal('196'), '0x9c869599a22ed61e237accfb6f37a08add389daf52dee645950476ec1fe8e7bf', '0x848c9026fa47d790074b9899b920f4762cbd7ebfad89145e391a1c43672f73ed', Decimal('14647249'), '0xB97048628DB6B661D4C2aA833e95Dbe1A905B280', Decimal('1'), datetime.datetime(2022, 4, 24, 11, 43, 18, tzinfo=psycopg2.tz.FixedOffsetTimezone(offset=0, name=None)), '0x48EceA69E8fe2158772Eaca4eb067E797F5Dcd91', '0x7079c7CcFF85824BC79Fe54A3367fDDB45B1f131', Decimal('2198.67943993')),
 ('0xc557a6cff362f6f2a51ab08a7f04ae9c8911147f6fd21d96fceaba715d8bb32d', [{'hex': '0x5d57f8382eBb02F897b004f2F79aD8233EC40da1', 'pos': 0, 'name': 'from', 'type': 'address'}, {'hex': '0x46705dfff24256421A05D056c29E81Bdc09723 ... (23 characters truncated) ... 'to', 'type': 'address'}, {'hex': '0xbb2d39ca4814c0000', 'num': 215800000000000000000, 'pos': 2, 'name': 'value', 'type': 'uint256', 'scaled': 215.8}], 'Transfer', Decimal('51'), Decimal('31'), '0xef084b9ba74e88df5f5f0c977a4bf57e01d81fac3abca629144fb63c1afc1d0b', '0xb740fe72afbb8dad60aefe3b0c6e484ce7260ffdb856faa8c908c27e8f7c68f6', Decimal('14645481'), '0xB97048628DB6B661D4C2aA833e95Dbe1A905B280', Decimal('1'), datetime.datetime(2022, 4, 24, 5, 0, 26, tzinfo=psycopg2.tz.FixedOffsetTimezone(offset=0, name=None)), '0x5d57f8382eBb02F897b004f2F79aD8233EC40da1', '0x46705dfff24256421A05D056c29E81Bdc09723B8', Decimal('215.8')),
 ('0x72bbbcd46a5ed788c06592f9ee5b2783d1e368d4659090fcb7f350ff2403b50a', [{'hex': '0x899147c5C5D7024afc81cf488a5BFEF4B6764780', 'pos': 0, 'name': 'from', 'type': 'address'}, {'hex': '0x5d57f8382eBb02F897b004f2F79aD8233EC40d ... (23 characters truncated) ... 'to', 'type': 'address'}, {'hex': '0xbb2d39ca4814c0000', 'num': 215800000000000000000, 'pos': 2, 'name': 'value', 'type': 'uint256', 'scaled': 215.8}], 'Transfer', Decimal('398'), Decimal('217'), '0x53e69066de8a3f3182ba36d6ce4df64576934ef627eb83d0eab564ac59f10c8d', '0xc58dca10c6e3b01e059fa2e42bb575f1b5fbb3a4058405e973c8401e427b7d77', Decimal('14645433'), '0xB97048628DB6B661D4C2aA833e95Dbe1A905B280', Decimal('1'), datetime.datetime(2022, 4, 24, 4, 50, 12, tzinfo=psycopg2.tz.FixedOffsetTimezone(offset=0, name=None)), '0x899147c5C5D7024afc81cf488a5BFEF4B6764780', '0x5d57f8382eBb02F897b004f2F79aD8233EC40da1', Decimal('215.8')),
 ('0x7f3b8c972fb3ca62ea047809782976a679a85700e3c74faf8545ec481f70e49c', [{'hex': '0xB8e957E5F39f01A058bA2EA0507c9a5Cddd8f3ED', 'pos': 0, 'name': 'from', 'type': 'address'}, {'hex': '0xFBb1b73C4f0BDa4f67dcA266ce6Ef42f520fBB ... (32 characters truncated) ... pe': 'address'}, {'hex': '0x150fbed23faeaeee000', 'num': 6216259214000000000000, 'pos': 2, 'name': 'value', 'type': 'uint256', 'scaled': 6216.259214}], 'Transfer', Decimal('63'), Decimal('17'), '0x63a5dfd3b07b27a744eebdd71f2a99c9fc0d0129d731d115578ee0e007977ceb', '0x332d2bf4dd0e2287f8cb618c3affdbfdedfaa15fc5bbbef2a32df31b54db7a6f', Decimal('14640670'), '0xB97048628DB6B661D4C2aA833e95Dbe1A905B280', Decimal('1'), datetime.datetime(2022, 4, 23, 11, 1, 55, tzinfo=psycopg2.tz.FixedOffsetTimezone(offset=0, name=None)), '0xB8e957E5F39f01A058bA2EA0507c9a5Cddd8f3ED', '0xFBb1b73C4f0BDa4f67dcA266ce6Ef42f520fBB98', Decimal('6216.259214')),
 ('0xf16ee76be2bbce6df0697019f04ac3d3779feec1a78f974caca6cbd059bf062d', [{'hex': '0x12a66D705d157f432A224daDf1F17eAEfF03a314', 'pos': 0, 'name': 'from', 'type': 'address'}, {'hex': '0xB8e957E5F39f01A058bA2EA0507c9a5Cddd8f3 ... (32 characters truncated) ... pe': 'address'}, {'hex': '0x150fbed23faeaeee000', 'num': 6216259214000000000000, 'pos': 2, 'name': 'value', 'type': 'uint256', 'scaled': 6216.259214}], 'Transfer', Decimal('55'), Decimal('41'), '0xdd3b994ac54e25914715b0b099b6e22fb600e7867a414ecdcd9dee08e3b65198', '0xdba232ee962b3d5722f5ae34f68eb85eb45ba133e14b4b11abd6a33afa122220', Decimal('14640653'), '0xB97048628DB6B661D4C2aA833e95Dbe1A905B280', Decimal('1'), datetime.datetime(2022, 4, 23, 10, 59, 5, tzinfo=psycopg2.tz.FixedOffsetTimezone(offset=0, name=None)), '0x12a66D705d157f432A224daDf1F17eAEfF03a314', '0xB8e957E5F39f01A058bA2EA0507c9a5Cddd8f3ED', Decimal('6216.259214')),
 ('0xb0b9d2e2c34f774230594898395caf1199056ad87121e8124b3648adb939ba7a', [{'hex': '0x49D0d3ab2296b17D367DF1cf189124220e5220E2', 'pos': 0, 'name': 'from', 'type': 'address'}, {'hex': '0x4Ec99C4cF82feB511c087065F0f837bf3aE997 ... (33 characters truncated) ... e': 'address'}, {'hex': '0xae9d3ae65e1fc1e400', 'num': 3221063089930000000000, 'pos': 2, 'name': 'value', 'type': 'uint256', 'scaled': 3221.06308993}], 'Transfer', Decimal('11'), Decimal('11'), '0x402338bc1853d7ab456c93c6e16c926255fea55e39b6263b9fdee3a1212aa082', '0x4113499719fc8b4ed64bf162f741cca24c0c4b830ed3fee570a6e50f555da993', Decimal('14639234'), '0xB97048628DB6B661D4C2aA833e95Dbe1A905B280', Decimal('1'), datetime.datetime(2022, 4, 23, 5, 29, 37, tzinfo=psycopg2.tz.FixedOffsetTimezone(offset=0, name=None)), '0x49D0d3ab2296b17D367DF1cf189124220e5220E2', '0x4Ec99C4cF82feB511c087065F0f837bf3aE997De', Decimal('3221.06308993')),
 ('0x3ded2288b55da392e0e46418d22f57caea01f0be1cc09e1dc5e77f6fe65ce957', [{'hex': '0xd3b1Ca9dfbB4ACf1669C60bD8587122144295b73', 'pos': 0, 'name': 'from', 'type': 'address'}, {'hex': '0x6EDF968DA408a9640b8865826429a977a11C50 ... (34 characters truncated) ... ': 'address'}, {'hex': '0x1857e114508af3328000', 'num': 114957881000000000000000, 'pos': 2, 'name': 'value', 'type': 'uint256', 'scaled': 114957.881}], 'Transfer', Decimal('271'), Decimal('159'), '0xa1cab2cc11efa0e707b1f6d5917c954a68de2cde603666674ff45145748278e0', '0xf116644ce8218c9b176946bc3301074783bcfa6e271274cf0638edb45c98cd8d', Decimal('14639122'), '0xB97048628DB6B661D4C2aA833e95Dbe1A905B280', Decimal('1'), datetime.datetime(2022, 4, 23, 5, 5, 47, tzinfo=psycopg2.tz.FixedOffsetTimezone(offset=0, name=None)), '0xd3b1Ca9dfbB4ACf1669C60bD8587122144295b73', '0x6EDF968DA408a9640b8865826429a977a11C5048', Decimal('114957.881')),
 ('0x9892539c86014d650ea01f912e740ab27ea0ef6edd1491cb9ab5b9510fd3c09b', [{'hex': '0x6cC5F688a315f3dC28A7781717a9A798a59fDA7b', 'pos': 0, 'name': 'from', 'type': 'address'}, {'hex': '0xd3b1Ca9dfbB4ACf1669C60bD8587122144295b ... (34 characters truncated) ... ': 'address'}, {'hex': '0x1857e114508af3328000', 'num': 114957881000000000000000, 'pos': 2, 'name': 'value', 'type': 'uint256', 'scaled': 114957.881}], 'Transfer', Decimal('18'), Decimal('6'), '0x9f90dd59a79b9dd188ffc542da441f5142dd2b6da2847c6c03c1eda1b847d887', '0x3f37786134e34f208d0b8fc06300a428df5ed0697a98ce005a430d5b40828b36', Decimal('14638966'), '0xB97048628DB6B661D4C2aA833e95Dbe1A905B280', Decimal('1'), datetime.datetime(2022, 4, 23, 4, 31, 14, tzinfo=psycopg2.tz.FixedOffsetTimezone(offset=0, name=None)), '0x6cC5F688a315f3dC28A7781717a9A798a59fDA7b', '0xd3b1Ca9dfbB4ACf1669C60bD8587122144295b73', Decimal('114957.881'))]

# 6. Find transaction for a given contract

In [ ]:
%%sql
SELECT * FROM tx
WHERE tx.to='0xB97048628DB6B661D4C2aA833e95Dbe1A905B280'
LIMIT 10

In [21]:
%%sql
Select * from balance 
where address = '0xB97048628DB6B661D4C2aA833e95Dbe1A905B280'
order by timestamp desc
limit 1;

 * postgresql://291ba738-366d-4650-a1ac-92590aace095:***@sql.anyblock.net:5432/ethereum_ethereum_mainnet
1 rows affected.

[('0xbda8b1532c009047a6bb51f83771367da3ba1690d140fd1291f37f70aa7775a6', '0xf65f9ba37025b420ebd8b6f0425ec92ca57c4cd6370ae5a781e9465a08fad85d', Decimal('14648937'), '0xB97048628DB6B661D4C2aA833e95Dbe1A905B280', Decimal('0'), datetime.datetime(2022, 4, 24, 18, 8, 8, tzinfo=psycopg2.tz.FixedOffsetTimezone(offset=0, name=None)))]