In [ ]:
from pymongo import MongoClient
import pandas as pd

!pip install dnspython
import dns

Collecting dnspython
  Downloading dnspython-2.2.1-py3-none-any.whl (269 kB)
     |████████████████████████████████| 269 kB 25.4 MB/s
Installing collected packages: dnspython
Successfully installed dnspython-2.2.1

In [ ]:
#Creating URL for connecting to Database on MongoDB
url = "mongodb://mathewjose47:BADM554@badm554-shard-00-00.44oda.mongodb.net:27017,badm554-shard-00-01.44oda.mongodb.net:27017,badm554-shard-00-02.44oda.mongodb.net:27017/myFirstDatabase?ssl=true&replicaSet=atlas-e16bus-shard-0&authSource=admin&retryWrites=true&w=majority"

#Initializing the client for MongoDB using the credentials
client = MongoClient(url)

In [ ]:
#Connecting to Yelp Database
db = client.get_database("Yelp")

In [ ]:
#Checking the record count for both the tables
reviewrecords = db.Review
reviewrecords.count_documents({})

597

In [ ]:
businessrecords = db.Business
businessrecords.count_documents({})

18939

In [ ]:
#Converting Document to Panda DF
business = pd.DataFrame(list(db.Business.find()))
business.head()

,_id,0,1,2,3,4,5,6,7,8,9,10,11,12
0,619b16e38a8d577abd2fbfd6,225,So4sUPedGUcyEMRAmDRgDw,Sabatino & Co,130 Newbury St,Boston,MA,02116,42.351049,-71.076655,4.5,8,0,"Cosmetics & Beauty Supply, Beauty & Spas, Shop..."
1,619b16e38a8d577abd2fbfe4,299,LHPzReyrFStB08KwMcyP2w,Boat Cruise Summer Series,200 Seaport Blvd,Boston,MA,02210,42.351367,-71.040491,3.0,5,1,"Event Planning & Services, Venues & Event Spac..."
2,619b16e38a8d577abd2fbfdf,310,Xz6aqENKlT4FU-ZBvrf_ow,Bugambilias,747 W Lancaster,Orlando,FL,32809,28.464982,-81.390952,4.5,43,1,"Restaurants, Mexican"
3,619b16e38a8d577abd2fbfd4,51,w4qVflIAbdklzG3mnKmQsg,Magical Pizza Express,"3262 Vineland Rd, Ste 106",Orlando,FL,32811,28.520500,-81.443950,1.0,8,1,"Italian, Restaurants"
4,619b16e38a8d577abd2fbfef,382,zjWGMm1SGJWeSaDpVVDU4g,Modell's Sporting Goods,480 Boylston St,Boston,MA,02116,42.350837,-71.073505,2.5,11,0,"Sports Wear, Sporting Goods, Shopping, Fashion"

In [ ]:
#Converting Business Document to Pandas DF
review = pd.DataFrame(list(db.Review.find()))
review.head()

,_id,review_id,user_id,business_id,stars,useful,funny,cool,text,date
0,619b16fa0e1d835e510a8be2,Kb_1Krtb5VgGdfivx7cmww,RXpxsLvw3v7LPhVAPNRvRw,paHbKmPjwirnIP7esoTPCQ,4,0,0,0,Good food and pleasant service. Self seating c...,1446775413000
1,619b16fa0e1d835e510a8b3a,KbXU4-SJqfxrW5-jcB73HQ,WXSCghMqWGY_tmfRrvlANQ,RDuPefU1ZBP6OyolshXvGw,5,1,0,0,Super cute retro-chic sewing shop! It has a sm...,1316989064000
2,619b16fa0e1d835e510a8c0e,iQ9m2jD9_ebtAbnyQxgmcg,57tf_RmT5o3BiFj2gpV-Jg,YCasSG_q_DdhWR6H1nhJ9A,4,0,0,0,My family's go to place for hot pot in Chinato...,1325602355000
3,619b16fa0e1d835e510a8b3d,pPbjcUiFIShdQq1mIOXc9Q,nkN_do3fJ9xekchVC-v68A,v5M1mNsDCQF0vLsRCMD0kQ,2,0,0,0,Called in flowers over the phone and I was pre...,1101963692000
4,619b16fa0e1d835e510a8b2c,WxrK52MRJy6Cxk_vOJeD1Q,9d22a-5XXvsZ55p04gI5jA,_gOz7-aHMyGUHOtjDrEv2w,2,4,2,0,"When we first arrived at the Coco Key, we were...",1505921907000

In [ ]:
#Outer joining the two DF using 12 (Business ID ) from Business, and business_id from review dfs
business_review = pd.merge(business, review, how = 'outer', left_on=['1'], right_on=['business_id'])

business_review.head()

,_id_x,0,1,2,3,4,5,6,7,8,...,_id_y,review_id,user_id,business_id,stars,useful,funny,cool,text,date
0,619b16e38a8d577abd2fbfd6,225,So4sUPedGUcyEMRAmDRgDw,Sabatino & Co,130 Newbury St,Boston,MA,02116,42.351049,-71.076655,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,619b16e38a8d577abd2fbfe4,299,LHPzReyrFStB08KwMcyP2w,Boat Cruise Summer Series,200 Seaport Blvd,Boston,MA,02210,42.351367,-71.040491,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,619b16e38a8d577abd2fbfdf,310,Xz6aqENKlT4FU-ZBvrf_ow,Bugambilias,747 W Lancaster,Orlando,FL,32809,28.464982,-81.390952,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,619b16e38a8d577abd2fbfd4,51,w4qVflIAbdklzG3mnKmQsg,Magical Pizza Express,"3262 Vineland Rd, Ste 106",Orlando,FL,32811,28.520500,-81.443950,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,619b16e38a8d577abd2fbfef,382,zjWGMm1SGJWeSaDpVVDU4g,Modell's Sporting Goods,480 Boylston St,Boston,MA,02116,42.350837,-71.073505,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#Filterting the rows which only contains "Restaurant" in category (12)
restaurant_review = business_review[business_review['12'].str.contains('Restaurant', na= False)]

restaurant_review.head(50)

,_id_x,0,1,2,3,4,5,6,7,8,...,_id_y,review_id,user_id,business_id,stars,useful,funny,cool,text,date
2,619b16e38a8d577abd2fbfdf,310,Xz6aqENKlT4FU-ZBvrf_ow,Bugambilias,747 W Lancaster,Orlando,FL,32809,28.464982,-81.390952,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,619b16e38a8d577abd2fbfd4,51,w4qVflIAbdklzG3mnKmQsg,Magical Pizza Express,"3262 Vineland Rd, Ste 106",Orlando,FL,32811,28.520500,-81.443950,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,619b16e38a8d577abd2fbfdb,220,y030N-DD6G7lfWHO4A6ezw,Saltgrass Steak House,8850 Vineland Ave,Orlando,FL,32821,28.373269,-81.503080,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,619b16e38a8d577abd2fc0ca,2039,YMwzbodNWxRxhY1Wz5gE1A,Roxy's Gourmet Grilled Cheese,,Boston,MA,02118,42.337797,-71.070576,...,619b16fa0e1d835e510a8d6a,O7naV-bXx_DfYNhXt0q_vQ,NSIz53C2Mwso64QijTUAlA,YMwzbodNWxRxhY1Wz5gE1A,5.0,0.0,0.0,0.0,Just had my first Roxy's Grilled Cheese. A-ma...,1.311871e+12
25,619b16e38a8d577abd2fbfd5,63,qbZJh9lR0gh4Wca96NQv9g,Chuck E. Cheese,7456 W Colonial Dr,Orlando,FL,32818,28.551335,-81.483167,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,619b16e38a8d577abd2fc05c,1283,3SUhbtzb49gJX9jvitGSFQ,Starring Rolls Cafe,"351 S Studio Dr, 351 S Studio Dr",Orlando,FL,32830,28.357769,-81.560086,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,619b16e38a8d577abd2fc065,1206,ZjizmUFYq7NP8N-FAbtzFw,Herrera's,11 Temple Pl,Boston,MA,02111,42.355270,-71.062568,...,619b16fa0e1d835e510a8ba5,Gv8L6uWIUG93HUlFn-Muvw,vKJyhAwueBFI5aGvD9ZcIw,ZjizmUFYq7NP8N-FAbtzFw,4.0,0.0,0.0,0.0,The Cart in the middle of DTC has good Burrito...,1.249331e+12
37,619b16e38a8d577abd2fc084,1508,oYpQs22iUr68hSiTh7pMRA,Restaurante Cesaria,266 Bowdoin St,Boston,MA,02122,42.306897,-71.066603,...,619b16fa0e1d835e510a8cd4,JqjzY6NVeQvDNw3OZOI6ow,yx2yxLnAr4iF84VApSqH7g,oYpQs22iUr68hSiTh7pMRA,5.0,1.0,0.0,0.0,Great spot for good authentic CV food and grea...,1.531458e+12
38,619b16e38a8d577abd2fc084,1508,oYpQs22iUr68hSiTh7pMRA,Restaurante Cesaria,266 Bowdoin St,Boston,MA,02122,42.306897,-71.066603,...,619b16fa0e1d835e510a8c87,knhj0AlVgnBFuuW6uK3mKA,jTH5nxMl0ri5l8Q3ehVU0g,oYpQs22iUr68hSiTh7pMRA,5.0,3.0,0.0,0.0,This place was great - and I was there only fo...,1.445608e+12
40,619b16e38a8d577abd2fc0d8,2201,DJjeZa1e6t3vrUr-biIWvQ,Mr K's Chinese Cuisine & Sushi,10395 Narcoossee Rd,Orlando,FL,32832,28.416230,-81.242359,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,619b16e38a8d577abd2fc0f9,2429,OTqUbo5LfSJXULw742jPJw,Olde Dixie Fried Chicken,5925 S Orange Ave,Orlando,FL,32809,28.472387,-81.368777,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,619b16e38a8d577abd2fbff1,436,xqxRL30UDtEP3v1E_x-SlA,Froggers Grill & Bar Southwest,6700 Conroy Windermere Rd,Orlando,FL,32835,28.493027,-81.473577,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,619b16e38a8d577abd2fc092,1598,4HiYQ84s7Mqy7iY8vp9_xA,Tortas El Rey,6151 S Orange Blossom Trl,Orlando,FL,32809,28.467363,-81.395989,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,619b16e38a8d577abd2fc0b5,1845,n15kZTmPh7DmSdAYk4Gf7Q,Al Capone Pizza Pasta & Meats,102 Broad St,Boston,MA,02110,42.357421,-71.052154,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,619b16e38a8d577abd2fc054,1062,0c8NZgbg1Q0vwXMPZTUlvA,Campo di Fiori,580 Commonwealth Ave,Boston,MA,02228,42.348810,-71.099424,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,619b16e38a8d577abd2fc16c,3331,9CUdYtLyfpYeF5S3HbgysA,Abhiruchi Indian Cuisine,6215 S Orange Blossom Trl,Orlando,FL,32809,28.466805,-81.396280,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54,619b16e38a8d577abd2fc1ae,3719,1VqftFBUMdktbt2MX5JUNQ,Boston Kitchen Pizza,1 Stuart St,Boston,MA,02116,42.351022,-71.063148,...,619b16fa0e1d835e510a8bdf,UWN6geLjvN9wImPCsxdRAg,sywRLyJCySBZGEyLi-9qyg,1VqftFBUMdktbt2MX5JUNQ,4.0,0.0,0.0,0.0,Their menu is pretty big and has a variety of ...,1.483330e+12
57,619b16e38a8d577abd2fc10c,2654,HiWtZgPBWPsbM43cSSeshw,Zoes Kitchen,"7341 W Sand Lake Rd, Ste 1081",Orlando,FL,32819,28.450389,-81.481276,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61,619b16e38a8d577abd2fbfce,88,EGZ0fhB9k0ZlI5sHda4vFw,Andy's Frozen Custard,5381 International Dr,Orlando,FL,32819,28.463278,-81.451181,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64,619b16e38a8d577abd2fbfeb,369,mw_qxZJraNu7Q6u0GkcMew,Chatham's Place,7575 Dr Phillips Blvd,Orlando,FL,32819,28.451882,-81.487383,...,619b16fa0e1d835e510a8b28,j_eh6Iw7qseluR-7KfZOMg,xpxWG7jQXZE6BcSeuIq4PQ,mw_qxZJraNu7Q6u0GkcMew,5.0,0.0,0.0,0.0,This is a five-star restaurant if ever I have ...,1.471039e+12
65,619b16e38a8d577abd2fbfeb,369,mw_qxZJraNu7Q6u0GkcMew,Chatham's Place,7575 Dr Phillips Blvd,Orlando,FL,32819,28.451882,-81.487383,...,619b16fa0e1d835e510a8b66,rmMBthBb4C3R25gFBDvEhw,Eb-fVFDzr_Xxtls89o-1zQ,mw_qxZJraNu7Q6u0GkcMew,4.0,0.0,0.0,0.0,Great atmosphere. The staff is excellent and t...,1.352173e+12
69,619b16e38a8d577abd2fc16f,3339,pHNvRjxSntENdQ3o2yq_VA,Frutta Bowls,13526 Village Park Dr,Orlando,FL,32837,28.369328,-81.426905,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73,619b16e38a8d577abd2fc0f8,2410,C4zr280r3ZvSpHrlNvzIyg,Pammie's Sammies,7000 Dr Phillips Blvd,Orlando,FL,32819,28.460227,-81.492341,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76,619b16e38a8d577abd2fbfee,388,N78TSwxdXeYZaKZsyvkryA,Code 10,1638 Washington St,Boston,MA,02118,42.337925,-71.074729,...,619b16fa0e1d835e510a8c81,sBMuXTWx1b-7YLjUiu2Mgw,6IJxGjTpzQHiAVn1C6qsrw,N78TSwxdXeYZaKZsyvkryA,1.0,2.0,0.0,1.0,We ordered after seeing it on grub hub and the...,1.415798e+12
78,619b16e38a8d577abd2fc06a,1333,IKdGrMfGsrpsQ_dPPjJttg,Sister Sorel,647 Tremont St,Boston,MA,02118,42.342247,-71.075429,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84,619b16e38a8d577abd2fc112,2688,LQ8rprZFKPuhlj8ndEPb0w,Il Mondo II,182 Massachusetts Ave,Boston,MA,02115,42.345845,-71.086706,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
86,619b16e38a8d577abd2fc1aa,3785,b5eA9mluSKUngvkJ4ZCILA,Chimi King Buffet,5731 S Orange Blossom Trl,Orlando,FL,32839,28.475253,-81.396198,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
91,619b16e38a8d577abd2fc00b,703,zQRbAOceJyC7xVBBRny2HQ,Bites & Bubbles,912 N Mills Ave,Orlando,FL,32803,28.557208,-81.364740,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
92,619b16e38a8d577abd2fc01d,738,LSmYTw4HvU0lDBK4Mg2KyQ,Shenannigans Bar,332 W Broadway,Boston,MA,02127,42.338394,-71.049801,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
94,619b16e38a8d577abd2fc0ab,1829,DdKSrl5LHtgXJ_-imoW4xg,Gatorville Poolside Bar & Grill,8001 International Dr,Orlando,FL,32819,28.448310,-81.468407,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98,619b16e38a8d577abd2fc133,2930,_io1bJDT7YaU1EpW3dSvPg,Giddy Up,1 Franklin Park Rd,Boston,MA,02121,42.302839,-71.087692,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
102,619b16e38a8d577abd2fbfd3,13,ufCxltuh56FF4-ZFZ6cVhg,Sister Honey's,247 E Michigan St,Orlando,FL,32806,28.513265,-81.374707,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
106,619b16e38a8d577abd2fc0bd,1942,i90jeBl_lLHzzuDLsxWJEA,Luke's Kitchen and Bar,640 S Orlando Ave,Orlando,FL,32751,28.622578,-81.363653,...,619b16fa0e1d835e510a8c4f,tzcM9LnvhHoubaI2mBdAYg,cLcDlWwaD8hebXrZRIazqQ,i90jeBl_lLHzzuDLsxWJEA,5.0,0.0,0.0,1.0,"I had lé cheeseburger, pink, naked fries which...",1.496777e+12
107,619b16e38a8d577abd2fc0bd,1942,i90jeBl_lLHzzuDLsxWJEA,Luke's Kitchen and Bar,640 S Orlando Ave,Orlando,FL,32751,28.622578,-81.363653,...,619b16fa0e1d835e510a8c8c,-Ljq2op7BF0I3n6s3H8axg,oi31qXbZNX6n0ViKRMTFRQ,i90jeBl_lLHzzuDLsxWJEA,1.0,1.0,0.0,0.0,Was not seated for 30 minutes when we had rese...,1.487511e+12
108,619b16e38a8d577abd2fc0bd,1942,i90jeBl_lLHzzuDLsxWJEA,Luke's Kitchen and Bar,640 S Orlando Ave,Orlando,FL,32751,28.622578,-81.363653,...,619b16fa0e1d835e510a8cd6,QbErd58Uab5Eoi5tyq_cdA,rCR_o-GPZf6D6ezk37COMw,i90jeBl_lLHzzuDLsxWJEA,5.0,0.0,0.0,0.0,Had a great meal at Luke's last night!! I was ...,1.532598e+12
109,619b16e38a8d577abd2fc014,763,rIdojqgqK1IcxYAyJhsLLg,Muse 24h Caffee,14100 Bonnet Creek Resort Ln,Orlando,FL,32821,28.355841,-81.534603,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
112,619b16e38a8d577abd2fc1a5,3767,rU_L6h3jZRn2qBkMfoYkjg,Greek Flame Taverna,"7600 Dr Phillips Blvd, Ste 4",Orlando,FL,32819,28.451428,-81.490565,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
113,619b16e38a8d577abd2fc1ac,3849,zyr68M7lzjC8iAk-c_RQdg,Denny's Diner,3957 S Kirkman Rd,Orlando,FL,32811,28.502836,-81.457951,...,619b16fa0e1d835e510a8c8e,WVpJiCYPXheRHm9tnckApA,SbRnWwJ1xPxeeSS7j9BJIQ,zyr68M7lzjC8iAk-c_RQdg,1.0,0.0,0.0,0.0,The food was good but Worst service I ever had...,1.401074e+12
121,619b16e38a8d577abd2fc18f,3583,zg9p8ZBFmEUCtfcBHNvzvg,City Diner,411 N Magnolia Ave,Orlando,FL,32801,28.548049,-81.376562,...,619b16fa0e1d835e510a8b2f,a1u34Q5FFAkgAeEIylMGWw,6T1zjAnnls2tE5rvqwtm9A,zg9p8ZBFmEUCtfcBHNvzvg,4.0,0.0,0.0,0.0,We ate at this place all three mornings we wer...,1.415800e+12
123,619b16e38a8d577abd2fc03d,1005,SALa3MhzFBKVGkzphbYrqQ,Sharon's Place,4905 S Orange Ave,Orlando,FL,32806,28.491256,-81.373160,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
125,619b16e38a8d577abd2fc06b,1340,1eyv_Nm2KHOmGGb7je21Ug,Fuzzy's Taco Shop,12241 East Colonial Dr,Orlando,FL,32826,28.566561,-81.195238,...,619b16fa0e1d835e510a8d15,n5OVIz-rcIao7jzs2gzrjg,0AmXl43xI0Soj75xet4Qcw,1eyv_Nm2KHOmGGb7je21Ug,5.0,1.0,0.0,0.0,I ordered the beef tacos (pretty basic of me) ...,1.535059e+12
129,619b16e38a8d577abd2fc180,3446,neYslCKmOIZMfrY0aqs-lg,La China,6473 S Chickasaw Trl,Orlando,FL,32829,28.470781,-81.266671,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
132,619b16e38a8d577abd2fc140,3021,XeGoe2eGu9K4qpL-MWGGPA,Tawakal Halal Cafe,389 Maverick St,Boston,MA,02128,42.365708,-71.029034,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
138,619b16e38a8d577abd2fc082,1506,p7TMPVrhCxG2Bi4HzZbqcQ,Churrascaria Brazilian Steakhouse,1000 Universal Studios Plz,Orlando,FL,32819,28.477249,-81.473566,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
142,619b16e38a8d577abd2fc1b1,3866,nGfl3yi7hwjrVso3wzG0wg,NYPD Pizza,2912 Edgewater Dr,Orlando,FL,32804,28.577683,-81.389971,...,619b16fa0e1d835e510a8cdb,ze2Go3d1IzhaZ5MfEW3nfw,AGC86sPcYRB8RARgxLvH9w,nGfl3yi7hwjrVso3wzG0wg,1.0,2.0,0.0,0.0,I called them to order delivery and this rude ...,1.420327e+12
144,619b16e38a8d577abd2fc1bd,4027,fzpEmlocGIoRy7YdM4Vweg,Daisy Buchanan's,240A Newbury St,Boston,MA,02116,42.349523,-71.081853,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
146,619b16e38a8d577abd2fc0b7,1890,CIuNre-2JhMOZLkaLeBtRA,Scoozi Newbury,237 Newbury St,Boston,MA,02116,42.349881,-71.082083,...,619b16fa0e1d835e510a8ba7,DDmbvPhrTKEhumEmX4hfTA,NtgXljFEPMAQx7pbgos93Q,CIuNre-2JhMOZLkaLeBtRA,4.0,0.0,0.0,0.0,A group of us were wandering around Boston on ...,1.303429e+12
149,619b16e38a8d577abd2fc127,2844,L0DY_tvx7chQerVmeIJcWQ,New China King,5709 Edgewater Dr,Orlando,FL,32810,28.609980,-81.413482,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
150,619b16e38a8d577abd2fc15f,3274,1DqH1jYITwUvlVut_YBApg,Chipotle Mexican Grill,2850 S Kirkman Rd,Orlando,FL,32811,28.512075,-81.459758,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
151,619b16e38a8d577abd2fc18d,3581,96RSYhKtJXU70XmKuhtHeQ,LA Boiling Seafood Crab & Crawfish,1242 E Colonial Dr,Orlando,FL,32803,28.552936,-81.362958,...,619b16fa0e1d835e510a8b6e,FUxfEvTKIEMtG36H_AYhtw,gO9Ie4xaS9A2OEP1OLROGQ,96RSYhKtJXU70XmKuhtHeQ,3.0,0.0,0.0,0.0,My daughter loves this place. The quality of t...,1.449282e+12